In [1]:
import numpy as np
import pandas as pd

In [4]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["Amit", "Neha", "Rahul", "Sneha", "Arjun"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 90, 78, 88, 76],
    "Passed": [True, True, True, True, False]
}

df = pd.DataFrame(data)
# print(df)
# df.to_csv("students.csv")
# df.to_csv('studentswithoutindex.csv', index=False)
# print(df.head(1))
# df.tail(2)
# df.describe()
hello = pd.read_csv('Hello.csv', index_col=0)
df1 = pd.DataFrame(hello)
print(hello)
df1.to_csv('how.csv')
x = pd.read_csv('how.csv')
x.index= [1,2,3]
print(x)

          Size  Age  Weight
Name
vishal  6 inch   21      80
aman    4 inch   22      75
ayush   1 inch   20      60
     Name    Size  Age  Weight
1  vishal  6 inch   21      80
2    aman  4 inch   22      75
3   ayush  1 inch   20      60

In [91]:
series = pd.Series(np.random.rand(10))
# print(series)
# print(type(series))
dataframe = pd.DataFrame(np.random.rand(100, 5) )
print(dataframe)
print(type(dataframe))
dataframe.describe()
dataframe.index
dataframe.columns

           0         1         2         3         4
0   0.755983  0.973666  0.927049  0.488713  0.160949
1   0.754775  0.640165  0.862254  0.003430  0.069582
2   0.813637  0.407810  0.015170  0.918264  0.138952
3   0.510112  0.703048  0.622028  0.202685  0.459126
4   0.344551  0.458523  0.413553  0.240637  0.734159
..       ...       ...       ...       ...       ...
95  0.985340  0.322082  0.623617  0.122288  0.288218
96  0.598256  0.134232  0.452050  0.578541  0.367799
97  0.473109  0.882476  0.726373  0.091674  0.923188
98  0.807220  0.156556  0.826718  0.996330  0.358020
99  0.875444  0.617894  0.406375  0.220532  0.507704

[100 rows x 5 columns]
<class 'pandas.DataFrame'>

RangeIndex(start=0, stop=5, step=1)

Converting Datafreame to numpy Array

In [ ]:
numpi = dataframe.to_numpy
print(type(numpi))
#apply any numpy operations

<class 'method'>

CHANGING ANY VALUE IN THE COLUMNS WILL CHANGE IT'S DATA TYPE TO OBJECT.

IN THIS CASE WE HAVE FLOAT DATA TYPE

FOR THE COLUMNS IT IS GENERALLY SAME FOR WHOLE COLUMNS BUT WE CAN CHANGE IT TOO

In [ ]:
newdf = dataframe # view of dataframe in newdf , changes will be shown with warning 
newdf = dataframe.copy() # Creates the copy of dataframe

#....................................................................LOC
print(newdf.head())
print(newdf.loc[0,0])
newdf.loc[0,0] = 0.123
newdf.head()
newdf.loc[[1,0],[0,2]]    #return a new data frame it won't chjange anything in newdf

          0         1         2         3         4
0  0.755983  0.973666  0.927049  0.488713  0.160949
1  0.754775  0.640165  0.862254  0.003430  0.069582
2  0.813637  0.407810  0.015170  0.918264  0.138952
3  0.510112  0.703048  0.622028  0.202685  0.459126
4  0.344551  0.458523  0.413553  0.240637  0.734159
0.7559827964515099

          0         2
1  0.754775  0.862254
0  0.123000  0.927049

In [100]:
dataframe.to_csv('dataset.csv')

CONVERT THE COLUMNS FROM 0-5 TO ABCDE

In [104]:
dataframe.columns = list("ABCDE")
dataframe.head()
# dataframe.T    #Transpose

          A         B         C         D         E
0  0.755983  0.973666  0.927049  0.488713  0.160949
1  0.754775  0.640165  0.862254  0.003430  0.069582
2  0.813637  0.407810  0.015170  0.918264  0.138952
3  0.510112  0.703048  0.622028  0.202685  0.459126
4  0.344551  0.458523  0.413553  0.240637  0.734159