EVERYTHIN ON EXCEL FILES

In [1]:
import numpy as np
import pandas as pd
import openpyxl 
import xlrd

In [2]:
dataset = pd.read_excel("Trial.xlsx", index_col=0)
print(dataset)

      A    1.1
1
2     B  678.0
3     A    1.3
4     B    1.4
5     A    1.5
6     B    1.6
7     A    1.7
8     B    1.8
9     A    1.9
10    B    2.0
11    A    2.1
12    B    2.2
13    A    2.3
14    B    2.4
15    A    2.5
16    B    2.6
17    A    2.7
18    B    2.8
19    A    2.9
20    B    3.0
21    A    3.1
22    B    3.2
23    A    3.3
24    B    3.4
25    A    3.5
26    B    3.6
1   123    NaN

Read the two sheets off the excel

In [14]:
dataset2 = pd.read_excel("trial.xlsx" , sheet_name="Sheet2", index_col=0)

dataset2
dataset2.head()
dataset2.tail()

     1.1
A
A    3.3
B    3.4
A    3.5
B    3.6
123  NaN

In [4]:
dataset2.iloc[0,1] = 678
dataset2.loc[1, 'A'] = "123"

Exporting Two sheets in the eexcel file

In [5]:
with pd.ExcelWriter("trial.xlsx") as writer:
    dataset.to_excel(writer, sheet_name="Sheet1", index=False)
    dataset2.to_excel(writer, sheet_name="Sheet2", index=False)

In [9]:
dataset
# dataset2

      A    1.1
1
2     B  678.0
3     A    1.3
4     B    1.4
5     A    1.5
6     B    1.6
7     A    1.7
8     B    1.8
9     A    1.9
10    B    2.0
11    A    2.1
12    B    2.2
13    A    2.3
14    B    2.4
15    A    2.5
16    B    2.6
17    A    2.7
18    B    2.8
19    A    2.9
20    B    3.0
21    A    3.1
22    B    3.2
23    A    3.3
24    B    3.4
25    A    3.5
26    B    3.6
1   123    NaN