LOC IS ONE OF THE MOSED USEFUL ,POWERFUL AND IMPORTANT FUNCTION

In [ ]:
import numpy as np 
import pandas as pd

In [ ]:
data = pd.read_csv("dataset.csv")
data.head()
data.columns= data.columns.astype(int) #THE COLUMNS VALUES 0,1,2,3 ARE STORED IN STRING FORM SO WE CONVERTED IT
data = data.drop(columns=["Unnamed: 0.1"])
data = data.drop(columns=["Unnamed: 0"])
data.to_csv("dataset.csv",index=False)

In [ ]:
type(data)
data.columns = data.columns.astype(int) #Convert Column to Integer Type
data.columns

.loc[row_selection, column_selection]

In [97]:
data.loc[[1,2],[0,1]] #1,2 rows of 0,1 columns
data.loc[[0,1,2],:]#ALL columns of 0,1,2 rows 
data.loc[:,[1]]#All rowws of 1st column
data.loc[:]#All Rows
data.loc[0,0] #Specific Value at 0th row and 0th column
# data.loc[(data.loc[:, 1] > 0.5)]
data.loc[(data[1] > 0.5, 1)] #Column 1 whose values are greater than 0.5
data.head(2)

          0         1         2         3         4
0  0.755983  0.973666  0.927049  0.488713  0.160949
1  0.754775  0.640165  0.862254  0.003430  0.069582

iloc[] is used when we want values based index of rows and columns (row/column name could be "A", "State"...)

In [ ]:
data.iloc[[0],[1]]

pandas.DataFrame

Data.drop() wont change the actual DataFrame it just return the copy or view 
TO actually change the dataset we have two options :
    1. We Can write :- data = data.drop(1) ----- Using Assignment Operator
    2. We can Use "inplace = True" ---- This will automatically reflect the changes in actual dataset

In [ ]:
data.drop(0)
data.drop(columns=1)
data.head()
data = data.drop(1)
data.head()
# here we can see the actual data is modified and 3 is removed but not 0 
data.drop(2,inplace=True)
data.head()
#Now 2nd row is also removed from the dataset

          0         1         2         3         4
0  0.755983  0.973666  0.927049  0.488713  0.160949
4  0.344551  0.458523  0.413553  0.240637  0.734159
5  0.589396  0.825738  0.245182  0.698622  0.676966
6  0.213847  0.651856  0.422519  0.567551  0.269152
7  0.690487  0.961346  0.590539  0.243796  0.477398

In [ ]:
data.drop(1,axis=0)
data.drop(1,axis=1)

          0         1         2         3         4
0  0.755983  0.973666  0.927049  0.488713  0.160949

In [123]:
data.reset_index()
data.reset_index(drop=True) #Removes the extra index column

           0         1         2         3         4
0   0.755983  0.973666  0.927049  0.488713  0.160949
1   0.344551  0.458523  0.413553  0.240637  0.734159
2   0.589396  0.825738  0.245182  0.698622  0.676966
3   0.213847  0.651856  0.422519  0.567551  0.269152
4   0.690487  0.961346  0.590539  0.243796  0.477398
..       ...       ...       ...       ...       ...
92  0.985340  0.322082  0.623617  0.122288  0.288218
93  0.598256  0.134232  0.452050  0.578541  0.367799
94  0.473109  0.882476  0.726373  0.091674  0.923188
95  0.807220  0.156556  0.826718  0.996330  0.358020
96  0.875444  0.617894  0.406375  0.220532  0.507704

[97 rows x 5 columns]

In [ ]:
data.dropna() #removes all Null Values written as 'pd.NaT'
data.dropna(how='all',axis=1) #Removes If all avlues in axis is null
data.isnull()
data.notnull()

        0      1      2      3      4
0   False  False  False  False  False
4   False  False  False  False  False
5   False  False  False  False  False
6   False  False  False  False  False
7   False  False  False  False  False
..    ...    ...    ...    ...    ...
95  False  False  False  False  False
96  False  False  False  False  False
97  False  False  False  False  False
98  False  False  False  False  False
99  False  False  False  False  False

[97 rows x 5 columns]

In [135]:
    #TO drop Duplicates 
data.drop_duplicates()
data.drop_duplicates(subset=[1]) #Subset will take it as argument while removing duplicates

           0         1         2         3         4
0   0.755983  0.973666  0.927049  0.488713  0.160949
4   0.344551  0.458523  0.413553  0.240637  0.734159
5   0.589396  0.825738  0.245182  0.698622  0.676966
6   0.213847  0.651856  0.422519  0.567551  0.269152
7   0.690487  0.961346  0.590539  0.243796  0.477398
..       ...       ...       ...       ...       ...
95  0.985340  0.322082  0.623617  0.122288  0.288218
96  0.598256  0.134232  0.452050  0.578541  0.367799
97  0.473109  0.882476  0.726373  0.091674  0.923188
98  0.807220  0.156556  0.826718  0.996330  0.358020
99  0.875444  0.617894  0.406375  0.220532  0.507704

[97 rows x 5 columns]