Let's Explore the DataSet

Operations :-
0.Add Index Column
1.Count Number of Male and Female Candidates 
2.number Of Candidates without Alternate phone number
3.
4.

In [1]:
import pandas as pd 
import numpy as np

In [23]:
df = pd.read_csv("Pending_Internship_Applications_Full (1210).csv",index_col=0 )

In [25]:
df.insert(0,"Index",range(1,len(df)+1))

In [26]:
df

,Index,Email,Phone,Alt Phone,Gender,Date of Birth,Category,Experience Level,Prev Internship,Prev Details,Address,City,State,Country,PIN Code,Heard From,Status,Applied At
Full Name,,,,,,,,,,,,,,,,,,
SriSachin J,1,sachinsri2401@gmail.com,9080629202,9080629202,Male,1/24/2007,UG / PG Student,Beginner,No,NaN,"18, Sami kannu Nagar Dippo Road Bharathipuram ...",Dindigul,Tamil Nadu,India,624003,Website,pending_payment,"5/13/2026, 2:32:11 PM"
Islam Basha,2,islambasha5229@gmail.com,9985617484,NaN,Male,3/18/2004,Graduate / Working Professional,Intermediate,No,NaN,"1-44b mail road gandlapenta\nHyderabad , Tolic...",Anantapur,Andhra Pradesh,India,515521,Website,pending_payment,"5/13/2026, 2:24:42 PM"
Shivam Rakesh Sharma,3,dshivamsharma.official@gmail.com,9579135195,NaN,Male,7/19/2001,Graduate / Working Professional,Beginner,No,NaN,"Ambegaon BK, Katraj, Pune",Pune,Maharashtra,India,411046,Social Media,pending_payment,"5/13/2026, 12:30:19 PM"
Yogita Sharma,4,yashibsr005@gmail.com,9457266299,NaN,Female,1/27/2008,UG / PG Student,Beginner,No,NaN,"Awas Vikas 2nd, near Anuj gas agency, anoopsha...",Bulandshahr,Uttar Pradesh,India,203001,Social Media,pending_payment,"5/13/2026, 12:01:18 PM"
Mohit,5,mohitkalwa384@gmail.com,9306430103,9306430103,Male,5/14/2008,Cybersecurity / Digital Forensics Enthusiast,Beginner,No,NaN,Vpo Sirsa\nSirsa,Sirsa,Haryana,India,125055,Friends / Referral,pending_payment,"5/13/2026, 11:59:17 AM"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
kanhaiya jee,1205,kanhaiyajee3722@gmail.com,9142755292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,At chak hazari kaliyachak Hilsa Nalanda Bihar ...,Hilsa,Bihar,NaN,NaN,NaN,pending_payment,"4/29/2026, 1:34:03 PM"
Meera Rushikesh Rasale,1206,meerarasale09@gmail.com,9503998314,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Shree Ram nagar takli road pandharpur,Pandharpur,Maharashtra,NaN,NaN,NaN,pending_payment,"4/29/2026, 1:32:52 PM"
Patil Shiva Deekshitha,1207,ps.deekshitha19@gmail.com,7075867074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"h.no.45-24B-3A,ashok nagar,near bluemoon super...",Kurnool,Andhra Pradesh,NaN,NaN,NaN,pending_payment,"4/29/2026, 1:32:36 PM"
Pasumarthi Kusuma Hareesh,1208,kusumahareesh999@gmail.com,8019785937,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Andhra Pradesh state, Visakhapatnam District, ...",Visakhapatnam,Andhra Pradesh,NaN,NaN,NaN,pending_payment,"4/29/2026, 1:32:03 PM"
Chryselle Christie Gomes,1209,chrysgomez18@gmail.com,9168346032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Madel\nB-4 Mahanagar Madel Grande Margao Goa, ...",Madgaon,Goa,NaN,NaN,NaN,pending_payment,"4/29/2026, 1:32:00 PM"

In [ ]:
df[df["Gender"]=="Female"]
# df[df["Gender"]=="Female"].count()

Index               239
Email               239
Phone               239
Alt Phone            96
Gender              239
Date of Birth       239
Category            239
Experience Level    239
Prev Internship     239
Prev Details          5
Address             239
City                239
State               239
Country             239
PIN Code            239
Heard From          239
Status              239
Applied At          239
dtype: int64

In [59]:
df[df["Gender"]=="Male"]

,Index,Email,Phone,Alt Phone,Gender,Date of Birth,Category,Experience Level,Prev Internship,Prev Details,Address,City,State,Country,PIN Code,Heard From,Status,Applied At
Full Name,,,,,,,,,,,,,,,,,,
SriSachin J,1,sachinsri2401@gmail.com,9080629202,9080629202,Male,1/24/2007,UG / PG Student,Beginner,No,NaN,"18, Sami kannu Nagar Dippo Road Bharathipuram ...",Dindigul,Tamil Nadu,India,624003,Website,pending_payment,"5/13/2026, 2:32:11 PM"
Islam Basha,2,islambasha5229@gmail.com,9985617484,NaN,Male,3/18/2004,Graduate / Working Professional,Intermediate,No,NaN,"1-44b mail road gandlapenta\nHyderabad , Tolic...",Anantapur,Andhra Pradesh,India,515521,Website,pending_payment,"5/13/2026, 2:24:42 PM"
Shivam Rakesh Sharma,3,dshivamsharma.official@gmail.com,9579135195,NaN,Male,7/19/2001,Graduate / Working Professional,Beginner,No,NaN,"Ambegaon BK, Katraj, Pune",Pune,Maharashtra,India,411046,Social Media,pending_payment,"5/13/2026, 12:30:19 PM"
Mohit,5,mohitkalwa384@gmail.com,9306430103,9306430103,Male,5/14/2008,Cybersecurity / Digital Forensics Enthusiast,Beginner,No,NaN,Vpo Sirsa\nSirsa,Sirsa,Haryana,India,125055,Friends / Referral,pending_payment,"5/13/2026, 11:59:17 AM"
Mohit,6,mohitkalwa384@gmail.com,9306430103,9306430103,Male,5/14/2008,Cybersecurity / Digital Forensics Enthusiast,Beginner,No,NaN,Vpo Sirsa\nSirsa,Sirsa,Haryana,India,125055,Friends / Referral,pending_payment,"5/13/2026, 11:59:08 AM"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Shubham Kumar Mahto,755,shubhlabh1009@gmail.com,6205747515,6205747515,Male,11/16/2004,UG / PG Student,Beginner,No,NaN,SIT COLONY DUGDA BOKARO JHARKHAND,Bokaro,Jharkhand,India,828404,Social Media,pending_payment,"4/30/2026, 6:08:46 PM"
Sai Ramesh Kumar,757,sai.rameshsultan@gmail.com,9430273950,NaN,Male,12/25/1994,Cybersecurity / Digital Forensics Enthusiast,Beginner,No,NaN,Chapra Saran Bihar,Chapra,Bihar,India,841302,Social Media,pending_payment,"4/30/2026, 6:05:24 PM"
Aman Rai,759,amrai858109@gmail.com,8581091274,NaN,Male,1/4/2004,Law Student (LLB / LLM),Intermediate,No,NaN,Greater Noida,Aliganj,Uttar Pradesh,India,203201,College,pending_payment,"4/30/2026, 5:59:37 PM"
Aman Rai,776,amrai858109@gmail.com,8581091274,NaN,Male,1/8/2004,UG / PG Student,Intermediate,No,NaN,Greater Noida,Afzalgarh,Uttar Pradesh,India,203201,College,pending_payment,"4/30/2026, 5:34:58 PM"
Aman Rai,815,amrai858109@gmail.com,8581091274,8581091274,Male,1/8/2004,Police Official,Beginner,No,NaN,Greater Noida,Agra,Uttar Pradesh,India,203201,College,pending_payment,"4/30/2026, 3:23:39 PM"

In [60]:
#number Of Candidates without Alternate phone number

# df["Alt Phone"].isna()
df["Alt Phone"].isna().sum()

np.int64(928)

In [70]:
df[df["Experience Level"]=="Beginner"]

,Index,Email,Phone,Alt Phone,Gender,Date of Birth,Category,Experience Level,Prev Internship,Prev Details,Address,City,State,Country,PIN Code,Heard From,Status,Applied At
Full Name,,,,,,,,,,,,,,,,,,
SriSachin J,1,sachinsri2401@gmail.com,9080629202,9080629202,Male,1/24/2007,UG / PG Student,Beginner,No,NaN,"18, Sami kannu Nagar Dippo Road Bharathipuram ...",Dindigul,Tamil Nadu,India,624003,Website,pending_payment,"5/13/2026, 2:32:11 PM"
Shivam Rakesh Sharma,3,dshivamsharma.official@gmail.com,9579135195,NaN,Male,7/19/2001,Graduate / Working Professional,Beginner,No,NaN,"Ambegaon BK, Katraj, Pune",Pune,Maharashtra,India,411046,Social Media,pending_payment,"5/13/2026, 12:30:19 PM"
Yogita Sharma,4,yashibsr005@gmail.com,9457266299,NaN,Female,1/27/2008,UG / PG Student,Beginner,No,NaN,"Awas Vikas 2nd, near Anuj gas agency, anoopsha...",Bulandshahr,Uttar Pradesh,India,203001,Social Media,pending_payment,"5/13/2026, 12:01:18 PM"
Mohit,5,mohitkalwa384@gmail.com,9306430103,9306430103,Male,5/14/2008,Cybersecurity / Digital Forensics Enthusiast,Beginner,No,NaN,Vpo Sirsa\nSirsa,Sirsa,Haryana,India,125055,Friends / Referral,pending_payment,"5/13/2026, 11:59:17 AM"
Mohit,6,mohitkalwa384@gmail.com,9306430103,9306430103,Male,5/14/2008,Cybersecurity / Digital Forensics Enthusiast,Beginner,No,NaN,Vpo Sirsa\nSirsa,Sirsa,Haryana,India,125055,Friends / Referral,pending_payment,"5/13/2026, 11:59:08 AM"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Shubham Kumar Mahto,755,shubhlabh1009@gmail.com,6205747515,6205747515,Male,11/16/2004,UG / PG Student,Beginner,No,NaN,SIT COLONY DUGDA BOKARO JHARKHAND,Bokaro,Jharkhand,India,828404,Social Media,pending_payment,"4/30/2026, 6:08:46 PM"
Mariyala Gayathri,756,mariyalagayathri2@gmail.com,7386719964,NaN,Female,11/19/2004,UG / PG Student,Beginner,No,NaN,Alkapuri colony,Rangareddi,Telangana,India,500035,Social Media,pending_payment,"4/30/2026, 6:06:42 PM"
Sai Ramesh Kumar,757,sai.rameshsultan@gmail.com,9430273950,NaN,Male,12/25/1994,Cybersecurity / Digital Forensics Enthusiast,Beginner,No,NaN,Chapra Saran Bihar,Chapra,Bihar,India,841302,Social Media,pending_payment,"4/30/2026, 6:05:24 PM"
Aman Rai,758,amrai858109@gmail.com,8581091274,NaN,Female,1/1/2004,Law Student (LLB / LLM),Beginner,No,NaN,Greater Noida,Akola,Uttar Pradesh,India,203201,College,pending_payment,"4/30/2026, 6:02:19 PM"
Aman Rai,815,amrai858109@gmail.com,8581091274,8581091274,Male,1/8/2004,Police Official,Beginner,No,NaN,Greater Noida,Agra,Uttar Pradesh,India,203201,College,pending_payment,"4/30/2026, 3:23:39 PM"

In [71]:
df[df["Experience Level"]=="Expert"]

Empty DataFrame
Columns: [Index, Email, Phone, Alt Phone, Gender, Date of Birth, Category, Experience Level, Prev Internship, Prev Details, Address, City, State, Country, PIN Code, Heard From, Status, Applied At]
Index: []

In [72]:
df[df["Experience Level"]=="Intermediate"]

,Index,Email,Phone,Alt Phone,Gender,Date of Birth,Category,Experience Level,Prev Internship,Prev Details,Address,City,State,Country,PIN Code,Heard From,Status,Applied At
Full Name,,,,,,,,,,,,,,,,,,
Islam Basha,2,islambasha5229@gmail.com,9985617484,NaN,Male,3/18/2004,Graduate / Working Professional,Intermediate,No,NaN,"1-44b mail road gandlapenta\nHyderabad , Tolic...",Anantapur,Andhra Pradesh,India,515521,Website,pending_payment,"5/13/2026, 2:24:42 PM"
Gautam Sood,9,soodgautam35@gmail.com,8882320469,NaN,Male,12/25/2001,Cybersecurity / Digital Forensics Enthusiast,Intermediate,Yes,Last year internship was amazing,A-2/285,Rohini,Delhi,India,110086,Social Media,pending_payment,"5/13/2026, 8:46:23 AM"
Vaibhav,17,vaibhavsharma.vee@gmail.com,9306368131,NaN,Male,1/20/2005,UG / PG Student,Intermediate,No,NaN,"Vill Lalpur Ki dhani, Near Opal Palace, Garhi ...",Rewari,Haryana,India,123401,Social Media,pending_payment,"5/12/2026, 11:02:17 PM"
Shweta Bhatia,25,bshweta176@gmail.com,9.19893E+11,NaN,Female,9/24/1996,Cybersecurity / Digital Forensics Enthusiast,Intermediate,No,NaN,"C 502, vimal nagar dream society, sv road, kan...",Mumbai,Maharashtra,India,400067,Friends / Referral,pending_payment,"5/12/2026, 8:50:34 PM"
Yasir Khan,26,khanyasirdude@gmail.com,8436802568,NaN,Male,7/5/2000,Cybersecurity / Digital Forensics Enthusiast,Intermediate,No,NaN,401 Swagat Unique\nOPP laxmi park Naya Nagar\n...,Mumbai,Maharashtra,India,401107,Social Media,pending_payment,"5/12/2026, 8:27:02 PM"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Joyita Sarkar,749,joyitas383@gmail.com,8583933935,8583933935,Female,10/16/2004,UG / PG Student,Intermediate,No,NaN,"Titagarh, Viveknaghar near kali mondir, Noooo",Kolkata,West Bengal,India,700119,Social Media,pending_payment,"4/30/2026, 6:18:12 PM"
Prajwal Raju Kunjekar,750,prajwalkunjekar1@gmail.com,99890654375,NaN,Male,10/2/2003,UG / PG Student,Intermediate,No,NaN,"Wagholi,Pune",Pune,Maharashtra,India,412207,Social Media,pending_payment,"4/30/2026, 6:17:07 PM"
Krishna Pratap Sharma,751,Krishnaxinbox@gmail.com,8700148600,8130191700,Male,12/29/2004,UG / PG Student,Intermediate,No,NaN,PRATAP VUHAR GHAZIABAD,Ghaziabad,Uttar Pradesh,India,201009,Social Media,pending_payment,"4/30/2026, 6:17:05 PM"
Aman Rai,759,amrai858109@gmail.com,8581091274,NaN,Male,1/4/2004,Law Student (LLB / LLM),Intermediate,No,NaN,Greater Noida,Aliganj,Uttar Pradesh,India,203201,College,pending_payment,"4/30/2026, 5:59:37 PM"
Aman Rai,776,amrai858109@gmail.com,8581091274,NaN,Male,1/8/2004,UG / PG Student,Intermediate,No,NaN,Greater Noida,Afzalgarh,Uttar Pradesh,India,203201,College,pending_payment,"4/30/2026, 5:34:58 PM"

In [73]:
df[df["Prev Internship"]=="Yes"]

,Index,Email,Phone,Alt Phone,Gender,Date of Birth,Category,Experience Level,Prev Internship,Prev Details,Address,City,State,Country,PIN Code,Heard From,Status,Applied At
Full Name,,,,,,,,,,,,,,,,,,
Gautam Sood,9,soodgautam35@gmail.com,8882320469,NaN,Male,12/25/2001,Cybersecurity / Digital Forensics Enthusiast,Intermediate,Yes,Last year internship was amazing,A-2/285,Rohini,Delhi,India,110086,Social Media,pending_payment,"5/13/2026, 8:46:23 AM"
Mayank Sargam,49,mayanksargam.1234@gmail.com,7209315794,NaN,Male,6/2/2004,Cybersecurity / Digital Forensics Enthusiast,Advanced,Yes,"Cyber zero , Amroha police Cyber security inte...","E 211 Beta 1 ,Tyagi Niwas Greater Noida",Gautam Buddha Nagar,Uttar Pradesh,India,201310,Social Media,pending_payment,"5/11/2026, 11:17:06 PM"
Mahin Patel,59,mahinpatel1404@gmail.com,7202026937,9875184689,Male,9/14/2004,UG / PG Student,Beginner,Yes,Participated in the expert session “Legal Shie...,"D/03 Arise Western , Nr. Umiya college , Sola ...",Ahmedabad,Gujarat,India,380060,Friends / Referral,pending_payment,"5/11/2026, 8:06:37 AM"
Sameer,79,sameerk20249@gmail.com,9350009825,9728668892,Male,12/27/2003,UG / PG Student,Intermediate,Yes,in 2025,"161/162 Block F1 Sultanpuri Delhi, 110086 near...",North West Delhi,Delhi,India,110086,Friends / Referral,pending_payment,"5/10/2026, 3:00:56 PM"
Naman Devnani,117,ndevnani756@gmail.com,9.176E+11,NaN,Male,11/7/2002,Graduate / Working Professional,Intermediate,Yes,CYBERZERO 1.0,"B/12 Parvati nagar, thakkarbapa nagar, near mu...",Ahmedabad,Gujarat,India,382350,Social Media,pending_payment,"5/10/2026, 12:04:24 AM"
Patel Harsh Devendrabhai,120,patelharsh203774@gmail.com,9016601261,NaN,Male,11/6/2004,UG / PG Student,Intermediate,Yes,Cyber Security,"1288, Idgahwad moh,kataragam darwaja, surat",Ahmedabad,Gujarat,India,382427,Workshop / Seminar,pending_payment,"5/9/2026, 11:24:30 PM"
Samod,139,samodbeserwal386@gmail.com,9034150676,9034150676,Male,4/5/1995,UG / PG Student,Intermediate,Yes,Yes,VOP dhana ladanpur Bhiwani,Bhiwani,Haryana,India,127021,College,pending_payment,"5/9/2026, 2:37:06 PM"
Harshit Singhal,153,harshitsinghal7790@gmail.com,7048980935,NaN,Male,4/17/2005,UG / PG Student,Beginner,Yes,Cyberzero Internship 2025,"B-103, Brave Hearts Society, Raj Nagar Extension",Ghaziabad,Uttar Pradesh,India,201017,Other,pending_payment,"5/8/2026, 11:09:44 PM"
Sameer,165,sameerk20249@gmail.com,9350009825,9728668892,Male,12/27/2003,UG / PG Student,Intermediate,Yes,In 2025,"161/162 Block F1 Sultanpuri Delhi, 110086 near...",Delhi,Delhi,India,110086,Friends / Referral,pending_payment,"5/8/2026, 9:41:34 AM"
sehaj,191,createbysehaj@gmail.com,6006580091,NaN,Male,10/17/2000,UG / PG Student,Intermediate,Yes,cyberzero 45 days internship,jammu,Akhnur,Jammu and Kashmir,India,181201,Social Media,pending_payment,"5/7/2026, 9:56:35 AM"
Bhanusree K,226,Ksree.9091@gmail.com,9030620794,NaN,Female,4/6/1991,Cybersecurity / Digital Forensics Enthusiast,Beginner,Yes,Simplilearn,"Place, LIGH 488, APHB COLONY, Moulali",Hyderabad,Telangana,India,500040,Social Media,pending_payment,"5/6/2026, 1:45:39 PM"
Lovekush,243,l936624@gmail.com,8376854250,8376854250,Male,6/18/2000,Cybersecurity / Digital Forensics Enthusiast,Intermediate,Yes,I learned,Dlf,East Delhi,Delhi,India,110095,Friends / Referral,pending_payment,"5/6/2026, 9:34:11 AM"
Sameer,324,sameerk20249@gmail.com,9350009825,9728668892,Male,12/27/2003,Law Enforcement Agency (LEA),Intermediate,Yes,IN 2025 AUG-OCT,"161/162 Block F1 Sultanpuri Delhi, 110086 near...",Delhi,Delhi,India,110086,Friends / Referral,pending_payment,"5/4/2026, 10:01:15 PM"
Zeeshan Sayyed,341,zsayyed367@gmail.com,9172128703,NaN,Male,4/23/2005,UG / PG Student,Beginner,Yes,Zeeshan,aurangabad,Aurangabad,Maharashtra,India,431001,College,pending_payment,"5/4/2026, 2:46:27 PM"
Hassane outman Medila,419,outmanimedilamy@gmail.com,7680820417,NaN,Male,1/2/2005,UG / PG Student,Beginner,Yes,No,"Sai Raghava Residency LB colony, Pedawaltair, ...",Visakhapatnam,Andhra Pradesh,India,530017,Friends / Referral,pending_payment,"5/3/2026, 4:48:26 PM"
Devendra kumar soni,437,devendrakumarsoni231@gmail.com,1234567891,1234567891,Male,2/20/2000,UG / PG Student,Beginner,Yes,Blue team internship from virtual cyber labs,Parasrampura jhunjhunu state rajasthan,Jhunjhunun,Rajasthan,India,333308,College,pending_payment,"5/3/2026, 12:43:04 PM"
Sneha Maileshwar,441,snehamaileshwar7@gmail.com,9373567896,9552968846,Female,11/17/2004,UG / PG Student,Beginner,Yes,Cyber suraksha for cyber shiksha,Karvenagar shahu colony lane no 2 opp aditya b...,Pune,Maharashtra,India,411052,Other,pending_payment,"5/3/2026, 12:26:52 PM"
Anshika Singh,449,anshikaforensic3105@gmail.com,8576000035,NaN,Female,5/31/2005,UG / PG Student,Beginner,Yes,Summer internship at Uttar Pradesh state insti...,SA4/709 kamla nagar colony daulatpur pandeypur...,Varanasi,Uttar Pradesh,India,221002,College,pending_payment,"5/3/2026, 10:38:22 AM"
Piyush Babele,456,piyushbabele25@gmail.com,9399820091,NaN,Male,7/8/2003,UG / PG Student,Intermediate,Yes,1,piyushbabele25@gmail.com,Bhopal,Madhya Pradesh,India,462037,Friends / Referral,pending_payment,"5/3/2026, 8:21:13 AM"
Sameer,470,sameerk20249@gmail.com,9350009825,9728668892,Male,12/27/2003,UG / PG Student,Intermediate,Yes,IN 2025 AUG-OCT,"161/162 Block F1 Sultanpuri Delhi, 110086 near...",North West Delhi,Delhi,India,110086,Friends / Referral,pending_payment,"5/3/2026, 12:52:27 AM"
Sachin Singh,483,sachin.singh611051@gmail.com,7024611051,NaN,Male,2/3/2005,UG / PG Student,Beginner,Yes,Cyberzero Internship,"Yadav bhawan,MH square near St. Sai convent Sc...",Gwalior,Madhya Pradesh,India,474006,Website,pending_payment,"5/2/2026, 10:13:15 PM"
SAMEER,524,sameerk20249@gmail.com,9350009825,9728668892,Male,12/27/2003,Graduate / Working Professional,Intermediate,Yes,IN 2025 AUG-OCT,"161/162 Block F1 Sultanpuri Delhi, 110086 near...",Delhi,Delhi,India,110086,Friends / Referral,pending_payment,"5/2/2026, 12:28:54 PM"
Deepika S,541,sdeepika2606@gmail.com,9840584712,9840584712,Female,6/26/2006,UG / PG Student,Intermediate,Yes,Elevate labs two months Cyber security intern,"4/772,9th cross street,bharathiyar nagar,neela...",Chennai,Tamil Nadu,India,600115,Social Media,pending_payment,"5/2/2026, 8:21:57 AM"
Ninitha P,663,ninithanini232@gmail.com,8590296706,NaN,Female,2/23/2003,Cybersecurity / Digital Forensics Enthusiast,Intermediate,Yes,"Cybersecurity Researcher & Developer , ZecurX ...","Thirumenhalli, Hennur",Bengaluru,Karnataka,India,560049,Social Media,pending_payment,"4/30/2026, 10:56:30 PM"
Ankit Gupta,689,kumarankitbux1234@gmail.com,7781099002,NaN,Male,6/6/2008,UG / PG Student,Beginner,Yes,No,BUXAR,Buxar,Bihar,India,802104,College,pending_payment,"4/30/2026, 10:06:42 PM"
Naman Devnani,702,ndevnani756@gmail.com,9.176E+11,NaN,Male,11/7/2002,Cybersecurity / Digital Forensics Enthusiast,Intermediate,Yes,CYBERZERO 1.0,"B/12 Parvati nagar, Thakkarbapa nagar, near mu...",Ahmedabad,Gujarat,India,382350,Social Media,pending_payment,"4/30/2026, 9:26:28 PM"
SeethaRam Praveen Damarla,746,seetharamdamarla06@gmail.com,9392820326,NaN,Male,3/17/2006,UG / PG Student,Intermediate,Yes,"Elevate labs,Codealpha",Bhavanarushi Nagar Chilakaluripet Andhra Prade...,Chilakalurupet,Andhra Pradesh,India,522616,Other,pending_payment,"4/30/2026, 6:29:11 PM"

In [74]:
df[df["Prev Internship"]=="No"]

,Index,Email,Phone,Alt Phone,Gender,Date of Birth,Category,Experience Level,Prev Internship,Prev Details,Address,City,State,Country,PIN Code,Heard From,Status,Applied At
Full Name,,,,,,,,,,,,,,,,,,
SriSachin J,1,sachinsri2401@gmail.com,9080629202,9080629202,Male,1/24/2007,UG / PG Student,Beginner,No,NaN,"18, Sami kannu Nagar Dippo Road Bharathipuram ...",Dindigul,Tamil Nadu,India,624003,Website,pending_payment,"5/13/2026, 2:32:11 PM"
Islam Basha,2,islambasha5229@gmail.com,9985617484,NaN,Male,3/18/2004,Graduate / Working Professional,Intermediate,No,NaN,"1-44b mail road gandlapenta\nHyderabad , Tolic...",Anantapur,Andhra Pradesh,India,515521,Website,pending_payment,"5/13/2026, 2:24:42 PM"
Shivam Rakesh Sharma,3,dshivamsharma.official@gmail.com,9579135195,NaN,Male,7/19/2001,Graduate / Working Professional,Beginner,No,NaN,"Ambegaon BK, Katraj, Pune",Pune,Maharashtra,India,411046,Social Media,pending_payment,"5/13/2026, 12:30:19 PM"
Yogita Sharma,4,yashibsr005@gmail.com,9457266299,NaN,Female,1/27/2008,UG / PG Student,Beginner,No,NaN,"Awas Vikas 2nd, near Anuj gas agency, anoopsha...",Bulandshahr,Uttar Pradesh,India,203001,Social Media,pending_payment,"5/13/2026, 12:01:18 PM"
Mohit,5,mohitkalwa384@gmail.com,9306430103,9306430103,Male,5/14/2008,Cybersecurity / Digital Forensics Enthusiast,Beginner,No,NaN,Vpo Sirsa\nSirsa,Sirsa,Haryana,India,125055,Friends / Referral,pending_payment,"5/13/2026, 11:59:17 AM"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sai Ramesh Kumar,757,sai.rameshsultan@gmail.com,9430273950,NaN,Male,12/25/1994,Cybersecurity / Digital Forensics Enthusiast,Beginner,No,NaN,Chapra Saran Bihar,Chapra,Bihar,India,841302,Social Media,pending_payment,"4/30/2026, 6:05:24 PM"
Aman Rai,758,amrai858109@gmail.com,8581091274,NaN,Female,1/1/2004,Law Student (LLB / LLM),Beginner,No,NaN,Greater Noida,Akola,Uttar Pradesh,India,203201,College,pending_payment,"4/30/2026, 6:02:19 PM"
Aman Rai,759,amrai858109@gmail.com,8581091274,NaN,Male,1/4/2004,Law Student (LLB / LLM),Intermediate,No,NaN,Greater Noida,Aliganj,Uttar Pradesh,India,203201,College,pending_payment,"4/30/2026, 5:59:37 PM"
Aman Rai,776,amrai858109@gmail.com,8581091274,NaN,Male,1/8/2004,UG / PG Student,Intermediate,No,NaN,Greater Noida,Afzalgarh,Uttar Pradesh,India,203201,College,pending_payment,"4/30/2026, 5:34:58 PM"
Aman Rai,815,amrai858109@gmail.com,8581091274,8581091274,Male,1/8/2004,Police Official,Beginner,No,NaN,Greater Noida,Agra,Uttar Pradesh,India,203201,College,pending_payment,"4/30/2026, 3:23:39 PM"

In [80]:
df["State"].unique()

<StringArray>
[                     'Tamil Nadu',                  'Andhra Pradesh',
                     'Maharashtra',                   'Uttar Pradesh',
                         'Haryana',                     'Uttarakhand',
                           'Delhi',                       'Telangana',
                          'Kerala',                       'Karnataka',
                         'Gujarat',                     'West Bengal',
                       'Rajasthan',                  'Madhya Pradesh',
               'Jammu and Kashmir',                          'Punjab',
                       'Jharkhand',                'Himachal Pradesh',
                           'Assam',                      'Cuanza Sul',
                          'Odisha',                           'Bihar',
                    'Chhattisgarh',                  'Central Region',
                   'Greater Accra',                 'Tirana District',
                      'Alexandria',                           'Sindh',
     'Islamabad Capital Territory',                        'Maritime',
                        'Maryland',                      'Chandigarh',
                 'Sharjah Emirate',                      'North West',
                         'Badghis', 'Abuja Federal Capital Territory',
              'Khyber Pakhtunkhwa',                         'Ontario',
                           'Tyrol',                  'Dhaka District',
                         'Tripura',                      'Artibonite',
                       'Southwest',                  'Waikato Region',
                          'Riyadh',                             'Goa']
Length: 46, dtype: str

In [81]:
df["Country"].unique()

<StringArray>
[               'India',               'Angola',                'Nepal',
                'Ghana',              'Albania',                'Egypt',
             'Pakistan',                 'Togo',        'United States',
 'United Arab Emirates',         'South Africa',          'Afghanistan',
              'Nigeria',                    nan]
Length: 14, dtype: str

In [82]:
df["City"].unique()

<StringArray>
[          'Dindigul',          'Anantapur',               'Pune',
        'Bulandshahr',              'Sirsa',            'Roorkee',
             'Rohini',              'Thane',             'Rampur',
          'Ghaziabad',
 ...
    'Rewari District', 'Thiruvananthapuram',            'Vidisha',
        'Tirthahalli',       'Jaggayyapeta',           'Pollachi',
              'Hilsa',         'Pandharpur',            'Kurnool',
            'Madgaon']
Length: 433, dtype: str

In [86]:
df["Heard From"].isna()
df["Heard From"].isna()
df["Heard From"].isna().sum()

np.int64(448)

In [87]:
df["Heard From"].unique()

<StringArray>
[           'Website',       'Social Media', 'Friends / Referral',
            'College',              'Other', 'Workshop / Seminar',
                  nan]
Length: 7, dtype: str

In [95]:
df["Prev Internship"]=="No"

Full Name
SriSachin J                    True
Islam Basha                    True
Shivam Rakesh Sharma           True
Yogita Sharma                  True
Mohit                          True
                              ...
kanhaiya jee                  False
Meera Rushikesh Rasale        False
Patil Shiva Deekshitha        False
Pasumarthi Kusuma Hareesh     False
Chryselle Christie Gomes      False
Name: Prev Internship, Length: 1209, dtype: bool

In [104]:
df["DOB"] = pd.to_datetime(df["Date of Birth"])
df["Age"] = (pd.Timestamp.today() - df["DOB"]).dt.days // 365

In [108]:
df["Age"]

Full Name
SriSachin J                   19.0
Islam Basha                   22.0
Shivam Rakesh Sharma          24.0
Yogita Sharma                 18.0
Mohit                         18.0
                              ...
kanhaiya jee                   NaN
Meera Rushikesh Rasale         NaN
Patil Shiva Deekshitha         NaN
Pasumarthi Kusuma Hareesh      NaN
Chryselle Christie Gomes       NaN
Name: Age, Length: 1209, dtype: float64

In [109]:
df["Age"].mean()

np.float64(21.724047306176082)