3. Filtering Operations
Questions:
Find all permits from zipcode 94102
Find rows where street number > 1000
Find all demolition permits
Find rows having missing zipcode
Find permits from specific neighborhoods

4. Sorting
Questions:
Sort by street number descending
Sort by creation date
Top zipcodes by number of permits
Multi-column sorting

In [1]:
import numpy as np 
import pandas as pd

In [16]:
df = pd.read_csv("Practice.csv")

C:\Users\Vishal Kumar\AppData\Local\Temp\ipykernel_27024\3348731116.py:1: DtypeWarning: Columns (0: Voluntary Soft-Story Retrofit, 1: TIDF Compliance) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Practice.csv")

In [ ]:
#Find all permits from zipcode 94102
df[df["Zipcode"]==94102]

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992
11,M805907,8,otc alterations permit,07/07/2017,0829,021,675,NaN,Fell,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Hayes Valley,94102.0,"(37.774914087334544, -122.42886839796792)",146961582526
29,M821847,8,otc alterations permit,08/22/2017,0326,001,165,NaN,Powell,St,...,NaN,NaN,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78625524960107, -122.40834431815433)",1475605447747
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198781,201802232105,3,additions alterations or repairs,02/23/2018,0856,012,100,NaN,Laguna,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,5.0,Hayes Valley,94102.0,"(37.77205253469414, -122.42520019493331)",149823683221
198819,M892967,8,otc alterations permit,02/23/2018,0347,017,333,NaN,Golden Gate,Av,...,NaN,NaN,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78128015571547, -122.41618114144971)",1498274470185
198843,M893167,8,otc alterations permit,02/23/2018,0852,042,221,NaN,Page,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Hayes Valley,94102.0,"(37.77363317295274, -122.42447661204797)",1498299459652
198875,201802232167,8,otc alterations permit,02/23/2018,0807,010,580,NaN,Hayes,St,...,NaN,NaN,1.0,constr type 1,NaN,5.0,Hayes Valley,94102.0,"(37.776756688343944, -122.4260292019233)",149833282001
198883,M893427,8,otc alterations permit,02/23/2018,0315,021,377,NaN,Geary,St,...,NaN,NaN,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78696971667916, -122.40936701144197)",149834069380

In [20]:
#Find rows where street number > 1000

df[df["Street Number"]>1000]

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
6,201706300814,8,otc alterations permit,06/30/2017,1739,020,1291,NaN,11th,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,5.0,Inner Sunset,94122.0,"(37.764145640138565, -122.46875112470363)",1468970403692
7,M803667,8,otc alterations permit,06/30/2017,4789,014,1465,NaN,Revere,Av,...,NaN,NaN,NaN,NaN,NaN,10.0,Bayview Hunters Point,94124.0,"(37.73005099023611, -122.38784938916618)",1469035175050
8,M804227,8,otc alterations permit,07/05/2017,1212,054,2094,NaN,Fell,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.772393498502595, -122.45231466824669)",1469198253772
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198888,201710110995,8,otc alterations permit,10/11/2017,0726,019,1410,NaN,Steiner,St,...,1.0,constr type 1,1.0,constr type 1,NaN,NaN,NaN,NaN,NaN,1483035367814
198892,201712045380,8,otc alterations permit,12/04/2017,1180,021,1543,NaN,Mcallister,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,148916691540
198893,201712055472,8,otc alterations permit,12/05/2017,1000,014,3018,NaN,Clay,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1489281258414
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,NaN,Montgomery,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489337276729
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,NaN,Indiana,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489539379952

In [21]:
#Find all demolition permits
df[df["Permit Type Definition"]=="demolitions"]

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992
95,201505297543,6,demolitions,05/29/2015,3780,001,502,NaN,07th,St,...,5.0,wood frame (5),NaN,NaN,NaN,6.0,South of Market,94103.0,"(37.77399389340962, -122.40478807349099)",1383267167552
104,201607273499,6,demolitions,07/27/2016,6580,036,4041,NaN,Cesar Chavez,St,...,5.0,wood frame (5),NaN,NaN,NaN,8.0,Noe Valley,94131.0,"(37.747266171580726, -122.43013955813504)",1431589462198
136,201706088787,6,demolitions,06/08/2017,3521,005,340,NaN,11th,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Mission,94103.0,"(37.771175863006434, -122.41354619526811)",1466170156723
205,201708084155,6,demolitions,08/08/2017,3728,086,1298,NaN,Howard,St,...,5.0,wood frame (5),NaN,NaN,NaN,6.0,South of Market,94103.0,"(37.77558396346592, -122.413028747729)",1473687359272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197117,201802080778,6,demolitions,02/08/2018,0667,020,1525,NaN,Pine,St,...,5.0,wood frame (5),NaN,NaN,NaN,3.0,Nob Hill,94109.0,"(37.78932105813934, -122.42082638965816)",149647978365
197150,201802080807,6,demolitions,02/08/2018,0076,020,1918,NaN,Powell,St,...,5.0,wood frame (5),NaN,NaN,NaN,3.0,North Beach,94133.0,"(37.80242483421091, -122.41098479661869)",1496514231040
197673,201802141218,6,demolitions,02/14/2018,6555,019,4250,NaN,26th,St,...,5.0,wood frame (5),NaN,NaN,NaN,8.0,Noe Valley,94114.0,"(37.74826881571773, -122.43497162261305)",1497083207404
198012,201802161494,6,demolitions,02/16/2018,3808,004,188,NaN,Hooper,St,...,2.0,constr type 2,NaN,NaN,NaN,10.0,Mission Bay,94107.0,"(37.7678881885801, -122.40031112920836)",1497441482245
198823,201802232134,6,demolitions,02/23/2018,2081,001,3701,NaN,Noriega,St,...,2.0,constr type 2,NaN,NaN,NaN,4.0,Sunset/Parkside,94122.0,"(37.752807918490184, -122.50357296075086)",1498279124987

In [29]:
#Find rows having missing zipcode

df[df["Zipcode"].isna()]

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
452,M866367,8,otc alterations permit,12/13/2017,0552,017,2550,NaN,Gough,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1490471235302
464,M845627,8,otc alterations permit,10/18/2017,5286A,021,2241,NaN,Jerrold,Av,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1490955510104
577,M364427,8,otc alterations permit,01/02/2013,0779,028,1235,NaN,Mcallister,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129220681682
731,201301047237,8,otc alterations permit,01/04/2013,6515,017,1387,NaN,Valencia,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1292365379064
864,201301077331,8,otc alterations permit,01/07/2013,3706,095,55,NaN,04th,St,...,1.0,constr type 1,1.0,constr type 1,NaN,NaN,NaN,NaN,NaN,1292500249105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,NaN,Montgomery,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489337276729
198896,201712055595,8,otc alterations permit,12/05/2017,0271,014,580,NaN,Bush,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,NaN,1489462354993
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,NaN,Indiana,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489539379952
198898,M863747,8,otc alterations permit,12/06/2017,0298,029,795,NaN,Sutter,St,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489608233656
198899,M864287,8,otc alterations permit,12/07/2017,0160,006,838,NaN,Pacific,Av,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489796283803

In [30]:
#Find permits from specific neighborhoods

df[df["Neighborhoods - Analysis Boundaries"]=="Tenderloin"]

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992
29,M821847,8,otc alterations permit,08/22/2017,0326,001,165,NaN,Powell,St,...,NaN,NaN,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78625524960107, -122.40834431815433)",1475605447747
120,201703302779,8,otc alterations permit,03/30/2017,0320,004,531,NaN,Hyde,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,6.0,Tenderloin,94109.0,"(37.78578517212513, -122.41669995016962)",1457912233858
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198414,201802211822,8,otc alterations permit,02/21/2018,0317,012,540,NaN,Jones,St,...,3.0,constr type 3,3.0,constr type 3,NaN,6.0,Tenderloin,94102.0,"(37.78636212836468, -122.4127665802486)",1497861233812
198622,201802221971,8,otc alterations permit,02/22/2018,0717,004,710,NaN,Ellis,St,...,3.0,constr type 3,3.0,constr type 3,NaN,6.0,Tenderloin,94109.0,"(37.78438499381087, -122.41802983321867)",1498074396310
198819,M892967,8,otc alterations permit,02/23/2018,0347,017,333,NaN,Golden Gate,Av,...,NaN,NaN,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78128015571547, -122.41618114144971)",1498274470185
198848,201802232152,8,otc alterations permit,02/23/2018,0717,003,719,NaN,Larkin,St,...,NaN,NaN,NaN,NaN,NaN,6.0,Tenderloin,94109.0,"(37.78454647870449, -122.41807225737581)",149830480432
198883,M893427,8,otc alterations permit,02/23/2018,0315,021,377,NaN,Geary,St,...,NaN,NaN,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78696971667916, -122.40936701144197)",149834069380

In [33]:
#Sort by street number descending

df["Street Number"].sort_values(ascending=False)

102439    8400
118418    8400
55716     8400
107325    8331
65704     8325
          ...
88498        1
197475       0
51215        0
156945       0
174263       0
Name: Street Number, Length: 198900, dtype: int64

In [34]:
#Sort by creation date
df["Permit Creation Date"].sort_values()

486       01/02/2013
562       01/02/2013
563       01/02/2013
564       01/02/2013
565       01/02/2013
             ...
110341    12/31/2015
110342    12/31/2015
110343    12/31/2015
110370    12/31/2015
110334    12/31/2015
Name: Permit Creation Date, Length: 198900, dtype: str

In [38]:
#Top zipcodes by number of permits

df["Number of Existing Stories"].sort_values(ascending=False)

50544     78.0
170855    63.0
170798    63.0
170315    63.0
198829    63.0
          ...
198884     NaN
198895     NaN
198897     NaN
198898     NaN
198899     NaN
Name: Number of Existing Stories, Length: 198900, dtype: float64

In [42]:
#Multi-column sorting


df.sort_values(["Street Number" ,"Zipcode"], ascending=[False,True])

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
55716,201407242054,8,otc alterations permit,07/24/2014,7126A,078,8400,NaN,Oceanview,Tr,...,5.0,wood frame (5),5.0,wood frame (5),NaN,7.0,Oceanview/Merced/Ingleside,94132.0,"(37.71048167244781, -122.46763746493815)",1349950472080
102439,201510159867,8,otc alterations permit,10/15/2015,7126A,153,8400,NaN,Oceanview,Tr,...,5.0,wood frame (5),5.0,wood frame (5),NaN,7.0,Oceanview/Merced/Ingleside,94132.0,"(37.71048167244781, -122.46763746493815)",1399524472250
118418,201603222754,8,otc alterations permit,03/22/2016,7126A,118,8400,NaN,Oceanview,Tr,...,5.0,wood frame (5),5.0,wood frame (5),NaN,7.0,Oceanview/Merced/Ingleside,94132.0,"(37.71048167244781, -122.46763746493815)",1416911472124
107325,201511303730,8,otc alterations permit,11/30/2015,1497,032,8331,NaN,Geary,Bl,...,5.0,wood frame (5),5.0,wood frame (5),NaN,1.0,Outer Richmond,94121.0,"(37.77867912806028, -122.50885355006393)",1404799101585
65704,201410280023,8,otc alterations permit,10/28/2014,1497,033,8325,NaN,Geary,Bl,...,5.0,wood frame (5),5.0,wood frame (5),NaN,1.0,Outer Richmond,94121.0,"(37.77868345272631, -122.50875855265706)",1360421101586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145895,201612225748,3,additions alterations or repairs,12/22/2016,1191,036,1,NaN,Shrader,St,...,1.0,constr type 1,1.0,constr type 1,NaN,NaN,NaN,NaN,NaN,1448430365892
156945,M785607,8,otc alterations permit,05/15/2017,3763,112,0,NaN,Situs To Be Assigned,NaN,...,NaN,NaN,NaN,NaN,NaN,6.0,Financial District/South Beach,94107.0,"(37.78291965523911, -122.39549956486029)",1463077485201
197475,M888387,8,otc alterations permit,02/12/2018,2601,001,0,NaN,Unknown,NaN,...,NaN,NaN,NaN,NaN,NaN,8.0,Haight Ashbury,94117.0,"(37.76836156598136, -122.44108966708585)",1496873138875
174263,201612013888,1,new construction,12/01/2016,5286A,004,0,NaN,Situs To Be Assigned,NaN,...,NaN,NaN,2.0,constr type 2,Y,10.0,Bayview Hunters Point,94124.0,"(37.744330245965145, -122.40166848292947)",1445952486475
51215,201406138346,8,otc alterations permit,06/13/2014,4519A,076,0,NaN,Galvez,Av,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1345214438789

In [ ]:
#Rows with more than 500 street number and Zipcode = 94102

df.loc[(df["Street Number"]>500) & (df["Zipcode"]==94102)]

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
4,201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992
11,M805907,8,otc alterations permit,07/07/2017,0829,021,675,NaN,Fell,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Hayes Valley,94102.0,"(37.774914087334544, -122.42886839796792)",146961582526
142,201706270487,8,otc alterations permit,06/27/2017,0297,028,515,NaN,Mason,St,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Nob Hill,94102.0,"(37.78831830234988, -122.41054888775284)",1468527493134
157,M807947,8,otc alterations permit,07/12/2017,0805,007,700,NaN,Hayes,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Hayes Valley,94102.0,"(37.7764535995205, -122.42813162705657)",147018481922
188,M814887,8,otc alterations permit,07/31/2017,0762,263,601,NaN,Van Ness,Av,...,NaN,NaN,NaN,NaN,NaN,5.0,Western Addition,94102.0,"(37.78138577762911, -122.42140632801414)",147259881205
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198173,M890687,8,otc alterations permit,02/16/2018,0806,014A,571,NaN,Ivy,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Hayes Valley,94102.0,"(37.77668208231201, -122.42746387534861)",1497575391498
198414,201802211822,8,otc alterations permit,02/21/2018,0317,012,540,NaN,Jones,St,...,3.0,constr type 3,3.0,constr type 3,NaN,6.0,Tenderloin,94102.0,"(37.78636212836468, -122.4127665802486)",1497861233812
198422,201802211828,8,otc alterations permit,02/21/2018,0744,013,939,NaN,Eddy,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,5.0,Western Addition,94102.0,"(37.7823159103887, -122.42311185803058)",1497869236842
198756,201802232083,8,otc alterations permit,02/23/2018,0807,010,580,NaN,Hayes,St,...,NaN,NaN,1.0,constr type 1,NaN,5.0,Hayes Valley,94102.0,"(37.776756688343944, -122.4260292019233)",149821082001
198875,201802232167,8,otc alterations permit,02/23/2018,0807,010,580,NaN,Hayes,St,...,NaN,NaN,1.0,constr type 1,NaN,5.0,Hayes Valley,94102.0,"(37.776756688343944, -122.4260292019233)",149833282001