Finding Missing Data & Delling or Filling Missing Data

1. Basic Exploration
Find:
Number of rows and columns
Column names
Datatypes
Memory usage
Unique values in each column

2. Missing Value Analysis (VERY IMPORTANT)
Questions:
Which columns have most NaNs?
Which rows are mostly empty?
Percentage missing per column?
Remove columns having > 50% NaNs
Fill missing values

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Practice.csv" , index_col=0)

C:\Users\Vishal Kumar\AppData\Local\Temp\ipykernel_24420\3772936206.py:1: DtypeWarning: Columns (0: Fire Only Permit, 1: Existing Construction Type) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Practice.csv" , index_col=0)

In [3]:
print(df)

               Permit Type            Permit Type Definition  \
Permit Number
201505065519             4                      sign - erect
201604195146             4                      sign - erect
201605278609             3  additions alterations or repairs
201611072166             8            otc alterations permit
201611283529             6                       demolitions
...                    ...                               ...
M862628                  8            otc alterations permit
201712055595             8            otc alterations permit
M863507                  8            otc alterations permit
M863747                  8            otc alterations permit
M864287                  8            otc alterations permit

              Permit Creation Date Block   Lot  Street Number  \
Permit Number
201505065519            05/06/2015  0326   023            140
201604195146            04/19/2016  0306   007            440
201605278609            05/27/2016  0595   203           1647
201611072166            11/07/2016  0156   011           1230
201611283529            11/28/2016  0342   001            950
...                            ...   ...   ...            ...
M862628                 12/05/2017  0113  017A           1228
201712055595            12/05/2017  0271   014            580
M863507                 12/06/2017  4318   019           1568
M863747                 12/06/2017  0298   029            795
M864287                 12/07/2017  0160   006            838

              Street Number Suffix Street Name Street Suffix  Unit  ...  \
Permit Number                                                       ...
201505065519                   NaN       Ellis            St   NaN  ...
201604195146                   NaN       Geary            St   0.0  ...
201605278609                   NaN     Pacific            Av   NaN  ...
201611072166                   NaN     Pacific            Av   0.0  ...
201611283529                   NaN      Market            St   NaN  ...
...                            ...         ...           ...   ...  ...
M862628                        NaN  Montgomery            St   NaN  ...
201712055595                   NaN        Bush            St   NaN  ...
M863507                        NaN     Indiana            St   NaN  ...
M863747                        NaN      Sutter            St   NaN  ...
M864287                        NaN     Pacific            Av   NaN  ...

              Existing Construction Type  \
Permit Number
201505065519                         3.0
201604195146                         3.0
201605278609                         1.0
201611072166                         5.0
201611283529                         3.0
...                                  ...
M862628                              NaN
201712055595                         5.0
M863507                              NaN
M863747                              NaN
M864287                              NaN

              Existing Construction Type Description  \
Permit Number
201505065519                           constr type 3
201604195146                           constr type 3
201605278609                           constr type 1
201611072166                          wood frame (5)
201611283529                           constr type 3
...                                              ...
M862628                                          NaN
201712055595                          wood frame (5)
M863507                                          NaN
M863747                                          NaN
M864287                                          NaN

              Proposed Construction Type  \
Permit Number
201505065519                         NaN
201604195146                         NaN
201605278609                         1.0
201611072166                         5.0
201611283529                         NaN
...                                  ...
M862628                              NaN
201712055595                         5.0
M863507                              NaN
M863747                              NaN
M864287                              NaN

              Proposed Construction Type Description Site Permit  \
Permit Number
201505065519                                     NaN         NaN
201604195146                                     NaN         NaN
201605278609                           constr type 1         NaN
201611072166                          wood frame (5)         NaN
201611283529                                     NaN         NaN
...                                              ...         ...
M862628                                          NaN         NaN
201712055595                          wood frame (5)         NaN
M863507                                          NaN         NaN
M863747                                          NaN         NaN
M864287                                          NaN         NaN

              Supervisor District Neighborhoods - Analysis Boundaries  \
Permit Number
201505065519                  3.0                          Tenderloin
201604195146                  3.0                          Tenderloin
201605278609                  3.0                        Russian Hill
201611072166                  3.0                            Nob Hill
201611283529                  6.0                          Tenderloin
...                           ...                                 ...
M862628                       NaN                                 NaN
201712055595                  NaN                                 NaN
M863507                       NaN                                 NaN
M863747                       NaN                                 NaN
M864287                       NaN                                 NaN

               Zipcode                                   Location  \
Permit Number
201505065519   94102.0  (37.785719256680785, -122.40852313194863)
201604195146   94102.0   (37.78733980600732, -122.41063199757738)
201605278609   94109.0    (37.7946573324287, -122.42232562979227)
201611072166   94109.0   (37.79595867909168, -122.41557405519474)
201611283529   94102.0   (37.78315261897309, -122.40950883997789)
...                ...                                        ...
M862628            NaN                                        NaN
201712055595       NaN                                        NaN
M863507            NaN                                        NaN
M863747            NaN                                        NaN
M864287            NaN                                        NaN

                   Record ID
Permit Number
201505065519   1380611233945
201604195146   1420164406718
201605278609   1424856504716
201611072166   1443574295566
201611283529    144548169992
...                      ...
M862628        1489337276729
201712055595   1489462354993
M863507        1489539379952
M863747        1489608233656
M864287        1489796283803

[198900 rows x 42 columns]

In [4]:
df.isnull()
df.head(5)

,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,Unit,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
Permit Number,,,,,,,,,,,,,,,,,,,,,
201505065519,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,NaN,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
201604195146,4,sign - erect,04/19/2016,0306,007,440,NaN,Geary,St,0.0,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,NaN,Pacific,Av,NaN,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,NaN,Pacific,Av,0.0,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
201611283529,6,demolitions,11/28/2016,0342,001,950,NaN,Market,St,NaN,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992

In [5]:
df.columns.size
df.columns.dtype

In [6]:
df.index
df.index.size
df.index.dtype
# df.drop("Index" , axis=1, inplace=True)

In [7]:
df.insert(0,"Index",range(1,len(df)+1))

In [8]:
# df.drop(df.query(df.isna()==True))
df.isna().sum()

Index                                          0
Permit Type                                    0
Permit Type Definition                         0
Permit Creation Date                           0
Block                                          0
Lot                                            0
Street Number                                  0
Street Number Suffix                      196684
Street Name                                    0
Street Suffix                               2768
Unit                                      169421
Unit Suffix                               196939
Description                                  290
Current Status                                 0
Current Status Date                            0
Filed Date                                     0
Issued Date                                14940
Completed Date                            101709
First Construction Document Date           14946
Structural Notification                   191978
Number of Existing Stories                 42784
Number of Proposed Stories                 42868
Voluntary Soft-Story Retrofit             198865
Fire Only Permit                          180073
Permit Expiration Date                     51880
Estimated Cost                             38066
Revised Cost                                6066
Existing Use                               41114
Existing Units                             51538
Proposed Use                               42439
Proposed Units                             50911
Plansets                                   37309
TIDF Compliance                           198898
Existing Construction Type                 43366
Existing Construction Type Description     43366
Proposed Construction Type                 43162
Proposed Construction Type Description     43162
Site Permit                               193541
Supervisor District                         1717
Neighborhoods - Analysis Boundaries         1725
Zipcode                                     1716
Location                                    1700
Record ID                                      0
dtype: int64

In [9]:
df.dropna(how="all",axis=1)
df.head(1)
#no rows or colums with all NaN values

,Index,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
Permit Number,,,,,,,,,,,,,,,,,,,,,
201505065519,1,4,sign - erect,05/06/2015,0326,023,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945

In [10]:
df.isna().sum()

Index                                          0
Permit Type                                    0
Permit Type Definition                         0
Permit Creation Date                           0
Block                                          0
Lot                                            0
Street Number                                  0
Street Number Suffix                      196684
Street Name                                    0
Street Suffix                               2768
Unit                                      169421
Unit Suffix                               196939
Description                                  290
Current Status                                 0
Current Status Date                            0
Filed Date                                     0
Issued Date                                14940
Completed Date                            101709
First Construction Document Date           14946
Structural Notification                   191978
Number of Existing Stories                 42784
Number of Proposed Stories                 42868
Voluntary Soft-Story Retrofit             198865
Fire Only Permit                          180073
Permit Expiration Date                     51880
Estimated Cost                             38066
Revised Cost                                6066
Existing Use                               41114
Existing Units                             51538
Proposed Use                               42439
Proposed Units                             50911
Plansets                                   37309
TIDF Compliance                           198898
Existing Construction Type                 43366
Existing Construction Type Description     43366
Proposed Construction Type                 43162
Proposed Construction Type Description     43162
Site Permit                               193541
Supervisor District                         1717
Neighborhoods - Analysis Boundaries         1725
Zipcode                                     1716
Location                                    1700
Record ID                                      0
dtype: int64

In [11]:
df.isna().sum()
df.drop(columns = df.columns[df.isna().sum()>1000] ,inplace=True)
# df = df.drop(columns=df.columns[df.isna().sum() > 10000])

In [12]:
df.isna().sum()

Index                       0
Permit Type                 0
Permit Type Definition      0
Permit Creation Date        0
Block                       0
Lot                         0
Street Number               0
Street Name                 0
Description               290
Current Status              0
Current Status Date         0
Filed Date                  0
Record ID                   0
dtype: int64

In [13]:
df.columns
df.index

Index(['201505065519', '201604195146', '201605278609', '201611072166',
       '201611283529', '201706149344', '201706300814', 'M803667', 'M804227',
       'M804767',
       ...
       '201711274822', '201711274844', '201712045380', '201712055472',
       '201712055493', 'M862628', '201712055595', 'M863507', 'M863747',
       'M864287'],
      dtype='str', name='Permit Number', length=198900)

In [14]:
backupDf = df

In [15]:
df.drop(columns=df.columns[df.isna().sum() > 10000])

,Index,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Name,Description,Current Status,Current Status Date,Filed Date,Record ID
Permit Number,,,,,,,,,,,,,
201505065519,1,4,sign - erect,05/06/2015,0326,023,140,Ellis,"ground fl facade: to erect illuminated, electr...",expired,12/21/2017,05/06/2015,1380611233945
201604195146,2,4,sign - erect,04/19/2016,0306,007,440,Geary,remove (e) awning and associated signs.,issued,08/03/2017,04/19/2016,1420164406718
201605278609,3,3,additions alterations or repairs,05/27/2016,0595,203,1647,Pacific,installation of separating wall,withdrawn,09/26/2017,05/27/2016,1424856504716
201611072166,4,8,otc alterations permit,11/07/2016,0156,011,1230,Pacific,repair dryrot & stucco at front of bldg.,complete,07/24/2017,11/07/2016,1443574295566
201611283529,5,6,demolitions,11/28/2016,0342,001,950,Market,demolish retail/office/commercial 3-story buil...,issued,12/01/2017,11/28/2016,144548169992
...,...,...,...,...,...,...,...,...,...,...,...,...,...
M862628,198896,8,otc alterations permit,12/05/2017,0113,017A,1228,Montgomery,street space,issued,12/05/2017,12/05/2017,1489337276729
201712055595,198897,8,otc alterations permit,12/05/2017,0271,014,580,Bush,fire alarm upgrade ref 201704123852,issued,12/06/2017,12/05/2017,1489462354993
M863507,198898,8,otc alterations permit,12/06/2017,4318,019,1568,Indiana,street space,issued,12/06/2017,12/06/2017,1489539379952
M863747,198899,8,otc alterations permit,12/06/2017,0298,029,795,Sutter,street space permit,issued,12/06/2017,12/06/2017,1489608233656
M864287,198900,8,otc alterations permit,12/07/2017,0160,006,838,Pacific,street space permit,issued,12/07/2017,12/07/2017,1489796283803

In [ ]:
df.drop(df[df.isna().sum(axis=1) >= 1].index)
# backupDf = df 
# NO Rows found which have more than 1 NaN value 
# so i have to remove that single row who have only only NaN value

In [20]:
df.index.unique()
df.describe()
df.info()

<class 'pandas.DataFrame'>
Index: 198900 entries, 201505065519 to M864287
Data columns (total 13 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Index                   198900 non-null  int64
 1   Permit Type             198900 non-null  int64
 2   Permit Type Definition  198900 non-null  str
 3   Permit Creation Date    198900 non-null  str
 4   Block                   198900 non-null  str
 5   Lot                     198900 non-null  str
 6   Street Number           198900 non-null  int64
 7   Street Name             198900 non-null  str
 8   Description             198610 non-null  str
 9   Current Status          198900 non-null  str
 10  Current Status Date     198900 non-null  str
 11  Filed Date              198900 non-null  str
 12  Record ID               198900 non-null  int64
dtypes: int64(4), str(9)
memory usage: 25.3+ MB

In [49]:
df.duplicated().sum()
df[df.duplicated()]
df.drop_duplicates(inplace=True)

In [74]:
df.isna().sum().idxmax() # Print name of cols with max NaN
df.isna().sum().max()

'Description'

In [61]:
descript = df.groupby("Description")

In [83]:
descript.head()

,Index,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Name,Description,Current Status,Current Status Date,Filed Date,Record ID
Permit Number,,,,,,,,,,,,,
201505065519,1,4,sign - erect,05/06/2015,0326,023,140,Ellis,"ground fl facade: to erect illuminated, electr...",expired,12/21/2017,05/06/2015,1380611233945
201604195146,2,4,sign - erect,04/19/2016,0306,007,440,Geary,remove (e) awning and associated signs.,issued,08/03/2017,04/19/2016,1420164406718
201605278609,3,3,additions alterations or repairs,05/27/2016,0595,203,1647,Pacific,installation of separating wall,withdrawn,09/26/2017,05/27/2016,1424856504716
201611072166,4,8,otc alterations permit,11/07/2016,0156,011,1230,Pacific,repair dryrot & stucco at front of bldg.,complete,07/24/2017,11/07/2016,1443574295566
201611283529,5,6,demolitions,11/28/2016,0342,001,950,Market,demolish retail/office/commercial 3-story buil...,issued,12/01/2017,11/28/2016,144548169992
...,...,...,...,...,...,...,...,...,...,...,...,...,...
201711274822,198891,3,additions alterations or repairs,11/27/2017,3803,001,185,Berry,"1st flr: suite 1000, construction of primary a...",filed,11/27/2017,11/27/2017,1488352388160
201711274844,198892,8,otc alterations permit,11/27/2017,0766,008,590,Van Ness,revision to 201608316525 for reflected ceiling,issued,12/08/2017,11/27/2017,148838081446
201712045380,198893,8,otc alterations permit,12/04/2017,1180,021,1543,Mcallister,soft story per sfbc chapter 4d 2016 iebc,issued,01/16/2018,12/04/2017,148916691540
201712055472,198894,8,otc alterations permit,12/05/2017,1000,014,3018,Clay,bathtub & shower tile replacement.,complete,01/22/2018,12/05/2017,1489281258414
201712055595,198897,8,otc alterations permit,12/05/2017,0271,014,580,Bush,fire alarm upgrade ref 201704123852,issued,12/06/2017,12/05/2017,1489462354993

In [85]:
backupDf= df
backupDf.to_csv("UpdatedDataSet.csv")

RESTARTING NEWDF WITH NEW CHANGES

In [82]:
newdf = pd.read_csv("Practice.csv")

C:\Users\Vishal Kumar\AppData\Local\Temp\ipykernel_24420\1951225982.py:1: DtypeWarning: Columns (0: Voluntary Soft-Story Retrofit, 1: TIDF Compliance) have mixed types. Specify dtype option on import or set low_memory=False.
  newdf = pd.read_csv("Practice.csv")

In [80]:
newdf.isna().sum()

Permit Number                                  0
Permit Type                                    0
Permit Type Definition                         0
Permit Creation Date                           0
Block                                          0
Lot                                            0
Street Number                                  0
Street Number Suffix                      196684
Street Name                                    0
Street Suffix                               2768
Unit                                      169421
Unit Suffix                               196939
Description                                  290
Current Status                                 0
Current Status Date                            0
Filed Date                                     0
Issued Date                                14940
Completed Date                            101709
First Construction Document Date           14946
Structural Notification                   191978
Number of Existing Stories                 42784
Number of Proposed Stories                 42868
Voluntary Soft-Story Retrofit             198865
Fire Only Permit                          180073
Permit Expiration Date                     51880
Estimated Cost                             38066
Revised Cost                                6066
Existing Use                               41114
Existing Units                             51538
Proposed Use                               42439
Proposed Units                             50911
Plansets                                   37309
TIDF Compliance                           198898
Existing Construction Type                 43366
Existing Construction Type Description     43366
Proposed Construction Type                 43162
Proposed Construction Type Description     43162
Site Permit                               193541
Supervisor District                         1717
Neighborhoods - Analysis Boundaries         1725
Zipcode                                     1716
Location                                    1700
Record ID                                      0
dtype: int64

In [87]:
#Which columns have most NaNs?
newdf.isna().sum().idxmax()

'TIDF Compliance'

In [90]:
#Which rows are mostly empty?
newdf.isna().sum(axis=1)
newdf.isna().sum(axis=1).idxmax()

116703

In [ ]:
#Percentage missing per column?
(newdf.isna().sum()/len(newdf))*100

Permit Number                              0.000000
Permit Type                                0.000000
Permit Type Definition                     0.000000
Permit Creation Date                       0.000000
Block                                      0.000000
Lot                                        0.000000
Street Number                              0.000000
Street Number Suffix                      98.885872
Street Name                                0.000000
Street Suffix                              1.391654
Unit                                      85.178984
Unit Suffix                               99.014077
Description                                0.145802
Current Status                             0.000000
Current Status Date                        0.000000
Filed Date                                 0.000000
Issued Date                                7.511312
Completed Date                            51.135747
First Construction Document Date           7.514329
Structural Notification                   96.519859
Number of Existing Stories                21.510307
Number of Proposed Stories                21.552539
Voluntary Soft-Story Retrofit             99.982403
Fire Only Permit                          90.534439
Permit Expiration Date                    26.083459
Estimated Cost                            19.138260
Revised Cost                               3.049774
Existing Use                              20.670689
Existing Units                            25.911513
Proposed Use                              21.336853
Proposed Units                            25.596280
Plansets                                  18.757667
TIDF Compliance                           99.998994
Existing Construction Type                21.802916
Existing Construction Type Description    21.802916
Proposed Construction Type                21.700352
Proposed Construction Type Description    21.700352
Site Permit                               97.305681
Supervisor District                        0.863248
Neighborhoods - Analysis Boundaries        0.867270
Zipcode                                    0.862745
Location                                   0.854701
Record ID                                  0.000000
dtype: float64

In [100]:
((newdf.isna().sum() / len(newdf)) * 100).max()

np.float64(99.9989944695827)

In [ ]:
#Find columns having > 50% NaNs
((newdf.isna().sum() / len(newdf)) * 100)

Permit Number                              0.000000
Permit Type                                0.000000
Permit Type Definition                     0.000000
Permit Creation Date                       0.000000
Block                                      0.000000
Lot                                        0.000000
Street Number                              0.000000
Street Number Suffix                      98.885872
Street Name                                0.000000
Street Suffix                              1.391654
Unit                                      85.178984
Unit Suffix                               99.014077
Description                                0.145802
Current Status                             0.000000
Current Status Date                        0.000000
Filed Date                                 0.000000
Issued Date                                7.511312
Completed Date                            51.135747
First Construction Document Date           7.514329
Structural Notification                   96.519859
Number of Existing Stories                21.510307
Number of Proposed Stories                21.552539
Voluntary Soft-Story Retrofit             99.982403
Fire Only Permit                          90.534439
Permit Expiration Date                    26.083459
Estimated Cost                            19.138260
Revised Cost                               3.049774
Existing Use                              20.670689
Existing Units                            25.911513
Proposed Use                              21.336853
Proposed Units                            25.596280
Plansets                                  18.757667
TIDF Compliance                           99.998994
Existing Construction Type                21.802916
Existing Construction Type Description    21.802916
Proposed Construction Type                21.700352
Proposed Construction Type Description    21.700352
Site Permit                               97.305681
Supervisor District                        0.863248
Neighborhoods - Analysis Boundaries        0.867270
Zipcode                                    0.862745
Location                                   0.854701
Record ID                                  0.000000
dtype: float64

In [107]:
newdf.loc[:,((newdf.isna().sum() / len(newdf)) * 100)>50]

,Street Number Suffix,Unit,Unit Suffix,Completed Date,Structural Notification,Voluntary Soft-Story Retrofit,Fire Only Permit,TIDF Compliance,Site Permit
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,0.0,NaN,07/24/2017,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
198895,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198896,NaN,NaN,NaN,NaN,NaN,NaN,Y,NaN,NaN
198897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198899,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Remove columns having > 50% NaNs
newdf = newdf.loc[:, ((newdf.isna().sum() / len(newdf)) * 100) <= 50]

In [110]:
newdf

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Name,Street Suffix,Description,...,Plansets,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,201505065519,4,sign - erect,05/06/2015,0326,023,140,Ellis,St,"ground fl facade: to erect illuminated, electr...",...,2.0,3.0,constr type 3,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1380611233945
1,201604195146,4,sign - erect,04/19/2016,0306,007,440,Geary,St,remove (e) awning and associated signs.,...,2.0,3.0,constr type 3,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1420164406718
2,201605278609,3,additions alterations or repairs,05/27/2016,0595,203,1647,Pacific,Av,installation of separating wall,...,2.0,1.0,constr type 1,1.0,constr type 1,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1424856504716
3,201611072166,8,otc alterations permit,11/07/2016,0156,011,1230,Pacific,Av,repair dryrot & stucco at front of bldg.,...,2.0,5.0,wood frame (5),5.0,wood frame (5),3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1443574295566
4,201611283529,6,demolitions,11/28/2016,0342,001,950,Market,St,demolish retail/office/commercial 3-story buil...,...,2.0,3.0,constr type 3,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",144548169992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198895,M862628,8,otc alterations permit,12/05/2017,0113,017A,1228,Montgomery,St,street space,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489337276729
198896,201712055595,8,otc alterations permit,12/05/2017,0271,014,580,Bush,St,fire alarm upgrade ref 201704123852,...,2.0,5.0,wood frame (5),5.0,wood frame (5),NaN,NaN,NaN,NaN,1489462354993
198897,M863507,8,otc alterations permit,12/06/2017,4318,019,1568,Indiana,St,street space,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489539379952
198898,M863747,8,otc alterations permit,12/06/2017,0298,029,795,Sutter,St,street space permit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489608233656
198899,M864287,8,otc alterations permit,12/07/2017,0160,006,838,Pacific,Av,street space permit,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1489796283803

In [ ]:
#Fill missing values (Integer filling)
for col in newdf.columns:
    if newdf.columns.dtype != 'object':
        newdf.fillna(0)
        print(newdf.fillna(0))
# newdf.isna()

       Permit Number  Permit Type            Permit Type Definition  \
0       201505065519            4                      sign - erect
1       201604195146            4                      sign - erect
2       201605278609            3  additions alterations or repairs
3       201611072166            8            otc alterations permit
4       201611283529            6                       demolitions
...              ...          ...                               ...
198895       M862628            8            otc alterations permit
198896  201712055595            8            otc alterations permit
198897       M863507            8            otc alterations permit
198898       M863747            8            otc alterations permit
198899       M864287            8            otc alterations permit

       Permit Creation Date Block   Lot  Street Number Street Name  \
0                05/06/2015  0326   023            140       Ellis
1                04/19/2016  0306   007            440       Geary
2                05/27/2016  0595   203           1647     Pacific
3                11/07/2016  0156   011           1230     Pacific
4                11/28/2016  0342   001            950      Market
...                     ...   ...   ...            ...         ...
198895           12/05/2017  0113  017A           1228  Montgomery
198896           12/05/2017  0271   014            580        Bush
198897           12/06/2017  4318   019           1568     Indiana
198898           12/06/2017  0298   029            795      Sutter
198899           12/07/2017  0160   006            838     Pacific

       Street Suffix                                        Description  ...  \
0                 St  ground fl facade: to erect illuminated, electr...  ...
1                 St            remove (e) awning and associated signs.  ...
2                 Av                    installation of separating wall  ...
3                 Av           repair dryrot & stucco at front of bldg.  ...
4                 St  demolish retail/office/commercial 3-story buil...  ...
...              ...                                                ...  ...
198895            St                                       street space  ...
198896            St                fire alarm upgrade ref 201704123852  ...
198897            St                                       street space  ...
198898            St                                street space permit  ...
198899            Av                                street space permit  ...

       Plansets Existing Construction Type  \
0           2.0                        3.0
1           2.0                        3.0
2           2.0                        1.0
3           2.0                        5.0
4           2.0                        3.0
...         ...                        ...
198895      0.0                        0.0
198896      2.0                        5.0
198897      0.0                        0.0
198898      0.0                        0.0
198899      0.0                        0.0

       Existing Construction Type Description Proposed Construction Type  \
0                               constr type 3                        0.0
1                               constr type 3                        0.0
2                               constr type 1                        1.0
3                              wood frame (5)                        5.0
4                               constr type 3                        0.0
...                                       ...                        ...
198895                                      0                        0.0
198896                         wood frame (5)                        5.0
198897                                      0                        0.0
198898                                      0                        0.0
198899                                      0                        0.0

       Proposed Construction Type Description  Supervisor District  \
0                                           0                  3.0
1                                           0                  3.0
2                               constr type 1                  3.0
3                              wood frame (5)                  3.0
4                                           0                  6.0
...                                       ...                  ...
198895                                      0                  0.0
198896                         wood frame (5)                  0.0
198897                                      0                  0.0
198898                                      0                  0.0
198899                                      0                  0.0

        Neighborhoods - Analysis Boundaries  Zipcode  \
0                                Tenderloin  94102.0
1                                Tenderloin  94102.0
2                              Russian Hill  94109.0
3                                  Nob Hill  94109.0
4                                Tenderloin  94102.0
...                                     ...      ...
198895                                    0      0.0
198896                                    0      0.0
198897                                    0      0.0
198898                                    0      0.0
198899                                    0      0.0

                                         Location      Record ID
0       (37.785719256680785, -122.40852313194863)  1380611233945
1        (37.78733980600732, -122.41063199757738)  1420164406718
2         (37.7946573324287, -122.42232562979227)  1424856504716
3        (37.79595867909168, -122.41557405519474)  1443574295566
4        (37.78315261897309, -122.40950883997789)   144548169992
...                                           ...            ...
198895                                          0  1489337276729
198896                                          0  1489462354993
198897                                          0  1489539379952
198898                                          0  1489608233656
198899                                          0  1489796283803

[198900 rows x 34 columns]
       Permit Number  Permit Type            Permit Type Definition  \
0       201505065519            4                      sign - erect
1       201604195146            4                      sign - erect
2       201605278609            3  additions alterations or repairs
3       201611072166            8            otc alterations permit
4       201611283529            6                       demolitions
...              ...          ...                               ...
198895       M862628            8            otc alterations permit
198896  201712055595            8            otc alterations permit
198897       M863507            8            otc alterations permit
198898       M863747            8            otc alterations permit
198899       M864287            8            otc alterations permit

       Permit Creation Date Block   Lot  Street Number Street Name  \
0                05/06/2015  0326   023            140       Ellis
1                04/19/2016  0306   007            440       Geary
2                05/27/2016  0595   203           1647     Pacific
3                11/07/2016  0156   011           1230     Pacific
4                11/28/2016  0342   001            950      Market
...                     ...   ...   ...            ...         ...
198895           12/05/2017  0113  017A           1228  Montgomery
198896           12/05/2017  0271   014            580        Bush
198897           12/06/2017  4318   019           1568     Indiana
198898           12/06/2017  0298   029            795      Sutter
198899           12/07/2017  0160   006            838     Pacific

       Street Suffix                                        Description  ...  \
0                 St  ground fl facade: to erect illuminated, electr...  ...
1                 St            remove (e) awning and associated signs.  ...
2                 Av                    installation of separating wall  ...
3                 Av           repair dryrot & stucco at front of bldg.  ...
4                 St  demolish retail/office/commercial 3-story buil...  ...
...              ...                                                ...  ...
198895            St                                       street space  ...
198896            St                fire alarm upgrade ref 201704123852  ...
198897            St                                       street space  ...
198898            St                                street space permit  ...
198899            Av                                street space permit  ...

       Plansets Existing Construction Type  \
0           2.0                        3.0
1           2.0                        3.0
2           2.0                        1.0
3           2.0                        5.0
4           2.0                        3.0
...         ...                        ...
198895      0.0                        0.0
198896      2.0                        5.0
198897      0.0                        0.0
198898      0.0                        0.0
198899      0.0                        0.0

       Existing Construction Type Description Proposed Construction Type  \
0                               constr type 3                        0.0
1                               constr type 3                        0.0
2                               constr type 1                        1.0
3                              wood frame (5)                        5.0
4                               constr type 3                        0.0
...                                       ...                        ...
198895                                      0                        0.0
198896                         wood frame (5)                        5.0
198897                                      0                        0.0
198898                                      0                        0.0
198899                                      0                        0.0

       Proposed Construction Type Description  Supervisor District  \
0                                           0                  3.0
1                                           0                  3.0
2                               constr type 1                  3.0
3                              wood frame (5)                  3.0
4                                           0                  6.0
...                                       ...                  ...
198895                                      0                  0.0
198896                         wood frame (5)                  0.0
198897                                      0                  0.0
198898                                      0                  0.0
198899                                      0                  0.0

        Neighborhoods - Analysis Boundaries  Zipcode  \
0                                Tenderloin  94102.0
1                                Tenderloin  94102.0
2                              Russian Hill  94109.0
3                                  Nob Hill  94109.0
4                                Tenderloin  94102.0
...                                     ...      ...
198895                                    0      0.0
198896                                    0      0.0
198897                                    0      0.0
198898                                    0      0.0
198899                                    0      0.0

                                         Location      Record ID
0       (37.785719256680785, -122.40852313194863)  1380611233945
1        (37.78733980600732, -122.41063199757738)  1420164406718
2         (37.7946573324287, -122.42232562979227)  1424856504716
3        (37.79595867909168, -122.41557405519474)  1443574295566
4        (37.78315261897309, -122.40950883997789)   144548169992
...                                           ...            ...
198895                                          0  1489337276729
198896                                          0  1489462354993
198897                                          0  1489539379952
198898                                          0  1489608233656
198899                                          0  1489796283803

[198900 rows x 34 columns]
       Permit Number  Permit Type            Permit Type Definition  \
0       201505065519            4                      sign - erect
1       201604195146            4                      sign - erect
2       201605278609            3  additions alterations or repairs
3       201611072166            8            otc alterations permit
4       201611283529            6                       demolitions
...              ...          ...                               ...
198895       M862628            8            otc alterations permit
198896  201712055595            8            otc alterations permit
198897       M863507            8            otc alterations permit
198898       M863747            8            otc alterations permit
198899       M864287            8            otc alterations permit

       Permit Creation Date Block   Lot  Street Number Street Name  \
0                05/06/2015  0326   023            140       Ellis
1                04/19/2016  0306   007            440       Geary
2                05/27/2016  0595   203           1647     Pacific
3                11/07/2016  0156   011           1230     Pacific
4                11/28/2016  0342   001            950      Market
...                     ...   ...   ...            ...         ...
198895           12/05/2017  0113  017A           1228  Montgomery
198896           12/05/2017  0271   014            580        Bush
198897           12/06/2017  4318   019           1568     Indiana
198898           12/06/2017  0298   029            795      Sutter
198899           12/07/2017  0160   006            838     Pacific

       Street Suffix                                        Description  ...  \
0                 St  ground fl facade: to erect illuminated, electr...  ...
1                 St            remove (e) awning and associated signs.  ...
2                 Av                    installation of separating wall  ...
3                 Av           repair dryrot & stucco at front of bldg.  ...
4                 St  demolish retail/office/commercial 3-story buil...  ...
...              ...                                                ...  ...
198895            St                                       street space  ...
198896            St                fire alarm upgrade ref 201704123852  ...
198897            St                                       street space  ...
198898            St                                street space permit  ...
198899            Av                                street space permit  ...

       Plansets Existing Construction Type  \
0           2.0                        3.0
1           2.0                        3.0
2           2.0                        1.0
3           2.0                        5.0
4           2.0                        3.0
...         ...                        ...
198895      0.0                        0.0
198896      2.0                        5.0
198897      0.0                        0.0
198898      0.0                        0.0
198899      0.0                        0.0

       Existing Construction Type Description Proposed Construction Type  \
0                               constr type 3                        0.0
1                               constr type 3                        0.0
2                               constr type 1                        1.0
3                              wood frame (5)                        5.0
4                               constr type 3                        0.0
...                                       ...                        ...
198895                                      0                        0.0
198896                         wood frame (5)                        5.0
198897                                      0                        0.0
198898                                      0                        0.0
198899                                      0                        0.0

       Proposed Construction Type Description  Supervisor District  \
0                                           0                  3.0
1                                           0                  3.0
2                               constr type 1                  3.0
3                              wood frame (5)                  3.0
4                                           0                  6.0
...                                       ...                  ...
198895                                      0                  0.0
198896                         wood frame (5)                  0.0
198897                                      0                  0.0
198898                                      0                  0.0
198899                                      0                  0.0

        Neighborhoods - Analysis Boundaries  Zipcode  \
0                                Tenderloin  94102.0
1                                Tenderloin  94102.0
2                              Russian Hill  94109.0
3                                  Nob Hill  94109.0
4                                Tenderloin  94102.0
...                                     ...      ...
198895                                    0      0.0
198896                                    0      0.0
198897                                    0      0.0
198898                                    0      0.0
198899                                    0      0.0

                                         Location      Record ID
0       (37.785719256680785, -122.40852313194863)  1380611233945
1        (37.78733980600732, -122.41063199757738)  1420164406718
2         (37.7946573324287, -122.42232562979227)  1424856504716
3        (37.79595867909168, -122.41557405519474)  1443574295566
4        (37.78315261897309, -122.40950883997789)   144548169992
...                                           ...            ...
198895                                          0  1489337276729
198896                                          0  1489462354993
198897                                          0  1489539379952
198898                                          0  1489608233656
198899                                          0  1489796283803

[198900 rows x 34 columns]
       Permit Number  Permit Type            Permit Type Definition  \
0       201505065519            4                      sign - erect
1       201604195146            4                      sign - erect
2       201605278609            3  additions alterations or repairs
3       201611072166            8            otc alterations permit
4       201611283529            6                       demolitions
...              ...          ...                               ...
198895       M862628            8            otc alterations permit
198896  201712055595            8            otc alterations permit
198897       M863507            8            otc alterations permit
198898       M863747            8            otc alterations permit
198899       M864287            8            otc alterations permit

       Permit Creation Date Block   Lot  Street Number Street Name  \
0                05/06/2015  0326   023            140       Ellis
1                04/19/2016  0306   007            440       Geary
2                05/27/2016  0595   203           1647     Pacific
3                11/07/2016  0156   011           1230     Pacific
4                11/28/2016  0342   001            950      Market
...                     ...   ...   ...            ...         ...
198895           12/05/2017  0113  017A           1228  Montgomery